### ISSUE TITLE
[Clear Command] Clear undo history after executing clear command

### ISSUE THREAD

**Issue by marcusngwenjian** [CS2103AUG2016-W15-C3/main#220]
Since clear command is irreversible, do clear the command history so that user are not allow to undo something they cleared.

Current implementation allows undo an add command, but no actual action takes place.

**Comment by turtle96** [comment]
It actually does clear the add commands, perhaps due to concurrent modification exception, it doesn't update the list in time.

The fix for concurrent modification exception to speed up updating history is pending review by @CS2103AUG2016-W15-C3/documentation  and @CS2103AUG2016-W15-C3/code-quality , PR #198.
